name: test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: ${{ matrix.lisp }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        lisp:
        - clasp
        - sbcl
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yitzchak/archlinux-cl:latest
    steps:
    - name: Checkout trivial-stream-column
      uses: actions/checkout@v4
      with:
        repository: yitzchak/trivial-stream-column
        path: trivial-stream-column
    - name: Checkout Incless
      uses: actions/checkout@v4
      with:
        repository: s-expressionists/Incless
        path: incless
    - name: Checkout Inravina
      uses: actions/checkout@v4
      with:
        repository: s-expressionists/Inravina
        path: inravina
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: invistra
    - name: Setup Lisp Environment
      run: |
        make-rc
        asdf-add
    - name: Run Regression Tests
      run: |
        lisp -i ${{ matrix.lisp }} -e "(ql:quickload :invistra-extrinsic/test)" -e "(asdf:test-system :invistra-extrinsic)"
    - name: Run ANSI Tests
      run: |
        lisp -i ${{ matrix.lisp }} -e "(ql:quickload :invistra-shim/test)" -e "(asdf:test-system :invistra-shim)"
